Drop TABLE IF EXISTS places;

CREATE TABLE IF NOT EXISTS places (
	`id` INT NOT NULL AUTO_INCREMENT,
    `CityId` VARCHAR(4) CHARACTER SET utf8,
    `CityName` VARCHAR(23) CHARACTER SET utf8,
    `CountryName` VARCHAR(13) CHARACTER SET utf8,
    `IataCode` VARCHAR(3) CHARACTER SET utf8,
    `Name` VARCHAR(39) CHARACTER SET utf8,
    `PlaceId` INT,
    `SkyscannerCode` VARCHAR(3) CHARACTER SET utf8,
    `Type` VARCHAR(7) CHARACTER SET utf8,
    PRIMARY KEY (id)
);

INSERT INTO places (CityId, CityName, CountryName, IataCode, Name, PlaceId, SkyscannerCode, Type) values
    ('ABEA','Allentown','United States','ABE','Allentown',40053,'ABE','Station'),
    ('ABIA','Abilene','United States','ABI','Abilene Municipal',40057,'ABI','Station'),
    ('ABQA','Albuquerque','United States','ABQ','Albuquerque',40065,'ABQ','Station'),
    ('ABRA','Aberdeen','United States','ABR','Aberdeen',40066,'ABR','Station'),
    ('ABYA','Albany','United States','ABY','Albany Dougherty County',40073,'ABY','Station'),
    ('ACKA','Nantucket','United States','ACK','Nantucket',40107,'ACK','Station'),
    ('ACTA','Waco','United States','ACT','Waco Municipal',40116,'ACT','Station'),
    ('ACVA','Arcata','United States','ACV','Arcata',40118,'ACV','Station'),
    ('AIYA','Atlantic City','United States','ACY','Atlantic City International',40121,'ACY','Station'),
    ('AEXA','Alexandria','United States','AEX','Alexandria Internation',40216,'AEX','Station'),
    ('AGSA','Augusta','United States','AGS','Augusta Bush Field',40307,'AGS','Station'),
    ('AIAA','Alliance','United States','AIA','Alliance',40385,'AIA','Station'),
    ('ALBA','Albany','United States','ALB','Albany',40530,'ALB','Station'),
    ('ALOA','Waterloo','United States','ALO','Waterloo',40543,'ALO','Station'),
    ('ALSA','Alamosa','United States','ALS','Alamosa',40547,'ALS','Station'),
    ('ALWA','Walla Walla','United States','ALW','Walla Walla',40551,'ALW','Station'),
    ('AMAA','Amarillo','United States','AMA','Amarillo International',40577,'AMA','Station'),
    ('ANCA','Anchorage','United States','ANC','Anchorage International',40627,'ANC','Station'),
    ('APNA','Alpena','United States','APN','Alpena',40734,'APN','Station'),
    ('ARTA','Watertown','United States','ART','Watertown',40836,'ART','Station'),
    ('ASEA','Aspen','United States','ASE','Aspen',40869,'ASE','Station'),
    ('ATLA','Atlanta','United States','ATL','Atlanta Hartsfield-Jackson',40924,'ATL','Station'),
    ('ATTA','Atmautluak','United States','ATT','Atmautluak',40932,'ATT','Station'),
    ('ATWA','Appleton','United States','ATW','Appleton',40935,'ATW','Station'),
    ('AUGA','Augusta','United States','AUG','Augusta',40967,'AUG','Station'),
    ('AUSA','Austin','United States','AUS','Austin-Bergstrom',40979,'AUS','Station'),
    ('AVLA','Asheville','United States','AVL','Asheville',41020,'AVL','Station'),
    ('AVPA','Wilkes-Barre','United States','AVP','Wilkes-Barre International',41024,'AVP','Station'),
    ('AZOA','Kalamazoo','United States','AZO','Kalamazoo',41215,'AZO','Station'),
    ('BCTA','Boca Raton','United States','BCT','Boca Raton',42420,'BCT','Station'),
    ('HFDA','Hartford','United States','BDL','Hartford Bradley International',42460,'BDL','Station'),
    ('BFFA','Scottsbluff','United States','BFF','Scottsbluff',42550,'BFF','Station'),
    ('BFLA','Bakersfield','United States','BFL','Bakersfield',42556,'BFL','Station'),
    ('BGMA','Binghamton','United States','BGM','Binghamton',42605,'BGM','Station'),
    ('BGRA','Bangor','United States','BGR','Bangor',42610,'BGR','Station'),
    ('BHBA','Bar Harbor','United States','BHB','Bar Harbor',42642,'BHB','Station'),
    ('BHMA','Birmingham','United States','BHM','Birmingham',42653,'BHM','Station'),
    ('BILA','Billings','United States','BIL','Billings',42700,'BIL','Station'),
    ('BISA','Bismarck','United States','BIS','Bismarck',42707,'BIS','Station'),
    ('BJIA','Bemidji','United States','BJI','Bemidji',42745,'BJI','Station'),
    ('HLIB','Branson','United States','BKG','Branson',42791,'BKG','Station'),
    ('BLIA','Bellingham','United States','BLI','Bellingham',42841,'BLI','Station'),
    ('BLVA','Belleville','United States','BLV','Belleville',42854,'BLV','Station'),
    ('BMGA','Bloomington','United States','BMG','Bloomington',42887,'BMG','Station'),
    ('BMIA','Bloomington-Normal','United States','BMI','Bloomington-Normal',42889,'BMI','Station'),
    ('BNAA','Nashville','United States','BNA','Nashville',42929,'BNA','Station'),
    ('BOIA','Boise','United States','BOI','Boise',42985,'BOI','Station'),
    ('BOSA','Boston','United States','BOS','Boston Logan International',42995,'BOS','Station'),
    ('BPTA','Beaumont','United States','BPT','Beaumont Jefferson County',43044,'BPT','Station'),
    ('SSIA','Brunswick','United States','BQK','Brunswick Glynco Jetport',43083,'BQK','Station'),
    ('BRDA','Brainerd','United States','BRD','Brainerd',43124,'BRD','Station'),
    ('BRLA','Burlington','United States','BRL','Burlington',43132,'BRL','Station'),
    ('BROA','Brownsville','United States','BRO','Brownsville',43135,'BRO','Station'),
    ('BRWA','Barrow','United States','BRW','Barrow Wiley Post / W.Rogers M',43143,'BRW','Station'),
    ('BTMA','Butte','United States','BTM','Butte',43229,'BTM','Station'),
    ('BTRA','Baton Rouge','United States','BTR','Baton Rouge Ryan',43234,'BTR','Station'),
    ('BTVA','Burlington','United States','BTV','Burlington',43238,'BTV','Station'),
    ('BUFA','Buffalo','United States','BUF','Buffalo Niagara',43270,'BUF','Station'),
    ('BURA','Burbank','United States','BUR','Burbank',43282,'BUR','Station'),
    ('WASA','Washington','United States','BWI','Baltimore Washington International',43369,'BWI','Station'),
    ('BZNA','Bozeman','United States','BZN','Bozeman',43518,'BZN','Station'),
    ('CAEA','Columbia','United States','CAE','Columbia Metropolitan',44613,'CAE','Station'),
    ('AKRB','Akron','United States','CAK','Akron / Canton Regional',44619,'CAK','Station'),
    ('CDCA','Cedar City','United States','CDC','Cedar City',44755,'CDC','Station'),
    ('CDVA','Cordova','United States','CDV','Cordova Mudhole Smith',44774,'CDV','Station'),
    ('CEZA','Cortez','United States','CEZ','Cortez',44826,'CEZ','Station'),
    ('CGIA','Cape Girardeau','United States','CGI','Cape Girardeau',44905,'CGI','Station'),
    ('CHAA','Chattanooga','United States','CHA','Chattanooga',44945,'CHA','Station'),
    ('CHOA','Charlottesville','United States','CHO','Charlottesville',44959,'CHO','Station'),
    ('CHSA','Charleston','United States','CHS','Charleston',44963,'CHS','Station'),
    ('CIDA','Cedar Rapids','United States','CID','Cedar Rapids',44996,'CID','Station'),
    ('SSMA','Sault Ste Marie','United States','CIU','Sault Ste Marie Chippewa County',45013,'CIU','Station'),
    ('CKBA','Clarksburg','United States','CKB','Clarksburg',45090,'CKB','Station'),
    ('CLEA','Cleveland','United States','CLE','Cleveland Hopkins International',45141,'CLE','Station'),
    ('CLLA','College Station','United States','CLL','College Station',45148,'CLL','Station'),
    ('CLTA','Charlotte','United States','CLT','Charlotte Douglas',45156,'CLT','Station'),
    ('CMHA','Columbus','United States','CMH','Port Columbus',45192,'CMH','Station'),
    ('CMIA','Champaign','United States','CMI','Champaign',45193,'CMI','Station'),
    ('CMXA','Hancock','United States','CMX','Hancock',45208,'CMX','Station'),
    ('CNYA','Moab','United States','CNY','Moab',45257,'CNY','Station'),
    ('CODA','Cody / Yellowstone','United States','COD','Cody / Yellowstone',45284,'COD','Station'),
    ('COSA','Colorado Springs','United States','COS','Colorado Springs Peterson Field',45299,'COS','Station'),
    ('COUA','Columbia','United States','COU','Columbia',45301,'COU','Station'),
    ('CPRA','Casper','United States','CPR','Casper',45346,'CPR','Station'),
    ('CRPA','Corpus Christi','United States','CRP','Corpus Christi International',45440,'CRP','Station'),
    ('CRWA','Charleston','United States','CRW','Charleston',45447,'CRW','Station'),
    ('CSGA','Columbus','United States','CSG','Columbus Metropolitain',45479,'CSG','Station'),
    ('CVGA','Cincinnati','United States','CVG','Cincinnati Northern Kentucky',45623,'CVG','Station'),
    ('AUWA','Wausau','United States','CWA','Wausau Central Wisconsin',45665,'CWA','Station'),
    ('CYSA','Cheyenne','United States','CYS','Cheyenne',45779,'CYS','Station'),
    ('DABA','Daytona Beach','United States','DAB','Daytona Beach',46914,'DAB','Station'),
    ('DFWA','Dallas','United States','DAL','Dallas Love Field',46924,'DAL','Station'),
    ('DAYA','Dayton','United States','DAY','Dayton International',46937,'DAY','Station'),
    ('DBQA','Dubuque','United States','DBQ','Dubuque',46977,'DBQ','Station'),
    ('WASA','Washington','United States','DCA','Washington Ronald Reagan',47009,'DCA','Station'),
    ('DDCA','Dodge City','United States','DDC','Dodge City',47059,'DDC','Station'),
    ('DENA','Denver','United States','DEN','Denver International',47118,'DEN','Station'),
    ('DFWA','Dallas','United States','DFW','Dallas Fort Worth International',47175,'DFW','Station'),
    ('DHNA','Dothan','United States','DHN','Dothan',47262,'DHN','Station'),
    ('DIKA','Dickinson','United States','DIK','Dickinson',47307,'DIK','Station'),
    ('DLHA','Duluth','United States','DLH','Duluth International',47448,'DLH','Station'),
    ('DROA','Durango','United States','DRO','Durango La Plata',47743,'DRO','Station'),
    ('DRTA','Del Rio','United States','DRT','Del Rio International',47748,'DRT','Station'),
    ('DSMA','Des Moines','United States','DSM','Des Moines',47789,'DSM','Station'),
    ('DTTA','Detroit','United States','DTW','Detroit Wayne County',47847,'DTW','Station'),
    ('EARA','Kearney','United States','EAR','Kearney',49234,'EAR','Station'),
    ('EATA','Wenatchee','United States','EAT','Wenatchee',49236,'EAT','Station'),
    ('PFNA','Panama City','United States','ECP','Northwest Florida Beaches International',49328,'ECP','Station'),
    ('EGEA','Vail','United States','EGE','Vail Eagle County',49509,'EGE','Station'),
    ('EKOA','Elko','United States','EKO','Elko',49711,'EKO','Station'),
    ('ELMA','Elmira','United States','ELM','Elmira',49757,'ELM','Station'),
    ('ELPA','El Paso','United States','ELP','El Paso International',49760,'ELP','Station'),
    ('ENAA','Kenai','United States','ENA','Kenai',49841,'ENA','Station'),
    ('ERIA','Erie','United States','ERI','Erie',50041,'ERI','Station'),
    ('ESCA','Escanaba','United States','ESC','Escanaba',50083,'ESC','Station'),
    ('EUGA','Eugene','United States','EUG','Eugene',50183,'EUG','Station'),
    ('EVVA','Evansville','United States','EVV','Evansville',50246,'EVV','Station'),
    ('EWNA','New Bern','United States','EWN','New Bern',50286,'EWN','Station'),
    ('NYCA','New York','United States','EWR','New York Newark',50290,'EWR','Station'),
    ('EYWA','Key West','United States','EYW','Key West International',50391,'EYW','Station'),
    ('FAIA','Fairbanks','United States','FAI','Fairbanks International',51529,'FAI','Station'),
    ('FARA','Fargo','United States','FAR','Fargo',51538,'FAR','Station'),
    ('FATA','Fresno','United States','FAT','Fresno Yosemite',51540,'FAT','Station'),
    ('FAYA','Fayetteville','United States','FAY','Fayetteville Municipal',51545,'FAY','Station'),
    ('FCAA','Kalispell','United States','FCA','Kalispell',51617,'FCA','Station'),
    ('GCNA','Grand Canyon','United States','FLG','Grand Canyon Pulliam Field',52055,'FLG','Station'),
    ('FLLA','Fort Lauderdale','United States','FLL','Fort Lauderdale International',52060,'FLL','Station'),
    ('FLOA','Florence','United States','FLO','Florence',52063,'FLO','Station'),
    ('FNTA','Flint','United States','FNT','Flint',52164,'FNT','Station'),
    ('FODA','Fort Dodge','United States','FOD','Fort Dodge',52196,'FOD','Station'),
    ('FSDA','Sioux Falls','United States','FSD','Sioux Falls',52388,'FSD','Station'),
    ('FSMA','Fort Smith','United States','FSM','Fort Smith',52397,'FSM','Station'),
    ('FWAA','Fort Wayne','United States','FWA','Fort Wayne',52577,'FWA','Station'),
    ('GCCA','Gillette','United States','GCC','Gillette',53923,'GCC','Station'),
    ('GCKA','Garden City','United States','GCK','Garden City',53931,'GCK','Station'),
    ('GEGA','Spokane','United States','GEG','Spokane International',54023,'GEG','Station'),
    ('GFKA','Grand Forks','United States','GFK','Grand Forks',54075,'GFK','Station'),
    ('GGGA','Longview','United States','GGG','East Texas Regional',54119,'GGG','Station'),
    ('GGWA','Glasgow','United States','GGW','Glasgow',54135,'GGW','Station'),
    ('GJTA','Grand Junction','United States','GJT','Grand Junction',54276,'GJT','Station'),
    ('GNVA','Gainesville','United States','GNV','Gainesville',54470,'GNV','Station'),
    ('GPTA','Gulfport','United States','GPT','Gulfport',54564,'GPT','Station'),
    ('GRBA','Green Bay','United States','GRB','Green Bay',54642,'GRB','Station'),
    ('ILEA','Killeen','United States','GRK','Killeen Gray AAF',54651,'GRK','Station'),
    ('GRRA','Grand Rapids','United States','GRR','Grand Rapids',54658,'GRR','Station'),
    ('GSOA','Greensboro / High Point','United States','GSO','Piedmont Triad International',54703,'GSO','Station'),
    ('GSPA','Greenville','United States','GSP','Greenville-Spartanburg',54704,'GSP','Station'),
    ('GTFA','Great Falls','United States','GTF','Great Falls International',54742,'GTF','Station'),
    ('UBSA','Columbus','United States','GTR','Columbus Golden Triangle Reg.',54754,'GTR','Station'),
    ('GUCA','Gunnison','United States','GUC','Gunnison',54787,'GUC','Station'),
    ('HDNA','Hayden','United States','HDN','Hayden',56286,'HDN','Station'),
    ('HHHA','Hilton Head','United States','HHH','Hilton Head',56472,'HHH','Station'),
    ('HIBA','Hibbing','United States','HIB','Hibbing',56514,'HIB','Station'),
    ('HLNA','Helena','United States','HLN','Helena',56670,'HLN','Station'),
    ('HNLA','Honolulu','United States','HNL','Honolulu International',56764,'HNL','Station'),
    ('HNMA','Hana','United States','HNM','Hana',56765,'HNM','Station'),
    ('HOBA','Hobbs','United States','HOB','Hobbs Lea County',56802,'HOB','Station'),
    ('HOMA','Homer','United States','HOM','Homer',56813,'HOM','Station'),
    ('HOUA','Houston','United States','HOU','Houston Hobby',56821,'HOU','Station'),
    ('HPNA','Westchester County','United States','HPN','Westchester County',56862,'HPN','Station'),
    ('HRLA','Harlingen','United States','HRL','Harlingen',56956,'HRL','Station'),
    ('HSVA','Huntsville','United States','HSV','Huntsville International',57014,'HSV','Station'),
    ('HTSA','Huntington','United States','HTS','Tri-State',57059,'HTS','Station'),
    ('HVNA','New Haven','United States','HVN','New Haven',57150,'HVN','Station'),
    ('HYAA','Hyannis','United States','HYA','Hyannis',57281,'HYA','Station'),
    ('HYSA','Hays','United States','HYS','Hays',57299,'HYS','Station'),
    ('WASA','Washington','United States','IAD','Washington Dulles',58436,'IAD','Station'),
    ('IAGA','Niagara Falls','United States','IAG','Niagara Falls',58439,'IAG','Station'),
    ('HOUA','Houston','United States','IAH','Houston George Bush Intercntl.',58440,'IAH','Station'),
    ('ICTA','Wichita','United States','ICT','Wichita Mid-Continent',58548,'ICT','Station'),
    ('IDAA','Idaho Falls','United States','IDA','Idaho Falls',58577,'IDA','Station'),
    ('ILMA','Wilmington','United States','ILM','Wilmington',58973,'ILM','Station'),
    ('IMTA','Iron Mountain','United States','IMT','Iron Mountain',59028,'IMT','Station'),
    ('INDA','Indianapolis','United States','IND','Indianapolis',59060,'IND','Station'),
    ('INLA','International Falls','United States','INL','International Falls',59068,'INL','Station'),
    ('IPLA','Imperial','United States','IPL','Imperial County',59164,'IPL','Station'),
    ('IPTA','Williamsport','United States','IPT','Williamsport',59172,'IPT','Station'),
    ('ISNA','Williston','United States','ISN','Williston',59310,'ISN','Station'),
    ('ISPA','Islip','United States','ISP','Islip',59312,'ISP','Station'),
    ('ITHA','Ithaca','United States','ITH','Ithaca',59352,'ITH','Station'),
    ('ITOA','Hilo','United States','ITO','Hilo',59359,'ITO','Station'),
    ('IWDA','Ironwood','United States','IWD','Ironwood',59492,'IWD','Station'),
    ('JACA','Jackson','United States','JAC','Jackson Hole',60739,'JAC','Station'),
    ('JANA','Jackson','United States','JAN','Jackson-Evers International',60750,'JAN','Station'),
    ('JAXA','Jacksonville','United States','JAX','Jacksonville International',60760,'JAX','Station'),
    ('NYCA','New York','United States','JFK','New York John F. Kennedy',60987,'JFK','Station'),
    ('JHMA','Kapalua','United States','JHM','Kapalua',61085,'JHM','Station'),
    ('JLNA','Joplin','United States','JLN','Joplin',61278,'JLN','Station'),
    ('JNUA','Juneau','United States','JNU','Juneau',61381,'JNU','Station'),
    ('KOAA','Kona','United States','KOA','Kona',63713,'KOA','Station'),
    ('KTNA','Ketchikan','United States','KTN','Ketchikan International',63966,'KTN','Station'),
    ('LANA','Lansing','United States','LAN','Lansing',65358,'LAN','Station'),
    ('LARA','Laramie','United States','LAR','Laramie',65362,'LAR','Station'),
    ('LASA','Las Vegas','United States','LAS','Las Vegas Mccarran',65363,'LAS','Station'),
    ('LAWA','Lawton','United States','LAW','Lawton',65367,'LAW','Station'),
    ('LAXA','Los Angeles','United States','LAX','Los Angeles International',65368,'LAX','Station'),
    ('LBBA','Lubbock','United States','LBB','Lubbock International',65394,'LBB','Station'),
    ('LBEA','Latrobe','United States','LBE','Latrobe',65397,'LBE','Station'),
    ('LBFA','North Platte','United States','LBF','North Platte',65398,'LBF','Station'),
    ('LBLA','Liberal','United States','LBL','Liberal',65404,'LBL','Station'),
    ('LCHA','Lake Charles','United States','LCH','Lake Charles',65448,'LCH','Station'),
    ('LEBA','Lebanon','United States','LEB','Lebanon',65538,'LEB','Station'),
    ('LEXA','Lexington','United States','LEX','Lexington Blue Grass',65560,'LEX','Station'),
    ('LFTA','Lafayette','United States','LFT','Lafayette',65604,'LFT','Station'),
    ('NYCA','New York','United States','LGA','New York LaGuardia',65633,'LGA','Station'),
    ('LGBA','Long Beach','United States','LGB','Long Beach Municipal',65634,'LGB','Station'),
    ('LIHA','Kauai Island','United States','LIH','Kauai Island Lihue',65736,'LIH','Station'),
    ('LITA','Little Rock','United States','LIT','Little Rock',65748,'LIT','Station'),
    ('LNKA','Lincoln','United States','LNK','Lincoln',65979,'LNK','Station'),
    ('LNYA','Lanai City','United States','LNY','Lanai City',65993,'LNY','Station'),
    ('LRDA','Laredo','United States','LRD','Laredo',66164,'LRD','Station'),
    ('LSEA','La Crosse','United States','LSE','La Crosse',66213,'LSE','Station'),
    ('LUPA','Kalaupapa','United States','LUP','Kalaupapa',66320,'LUP','Station'),
    ('LWBA','Lewisburg','United States','LWB','Lewisburg',66402,'LWB','Station'),
    ('LWSA','Lewiston','United States','LWS','Lewiston-Nez Perce County',66419,'LWS','Station'),
    ('LYHA','Lynchburg','United States','LYH','Lynchburg',66504,'LYH','Station'),
    ('MAFA','Midland','United States','MAF','Midland Odessa Regional',67654,'MAF','Station'),
    ('MBSA','Midland','United States','MBS','Midland',67715,'MBS','Station'),
    ('MCEA','Merced','United States','MCE','Merced Municipal Arpt',67749,'MCE','Station'),
    ('MKCA','Kansas City','United States','MCI','Kansas City International',67753,'MCI','Station'),
    ('MCKA','Mccook','United States','MCK','Mccook',67755,'MCK','Station'),
    ('ORLB','Orlando','United States','MCO','Orlando International',67759,'MCO','Station'),
    ('MCWA','Mason City','United States','MCW','Mason City',67767,'MCW','Station'),
    ('HARA','Harrisburg','United States','MDT','Harrisburg International',67812,'MDT','Station'),
    ('CHIA','Chicago','United States','MDW','Chicago Midway',67815,'MDW','Station'),
    ('MEIA','Meridian','United States','MEI','Meridian',67849,'MEI','Station'),
    ('MEMA','Memphis','United States','MEM','Memphis International',67853,'MEM','Station'),
    ('MFEA','Mcallen','United States','MFE','Mcallen',67893,'MFE','Station'),
    ('MFRA','Medford','United States','MFR','Medford',67906,'MFR','Station'),
    ('MGMA','Montgomery','United States','MGM','Montgomery Dannelly Fld',67949,'MGM','Station'),
    ('MHKA','Manhattan','United States','MHK','Manhattan',67995,'MHK','Station'),
    ('MHTA','Manchester','United States','MHT','Manchester',68004,'MHT','Station'),
    ('MIAA','Miami','United States','MIA','Miami International',68033,'MIA','Station'),
    ('MKEA','Milwaukee','United States','MKE','Milwaukee General Mitchell',68133,'MKE','Station'),
    ('MKGA','Muskegon','United States','MKG','Muskegon',68135,'MKG','Station'),
    ('MKKA','Hoolehua','United States','MKK','Hoolehua',68139,'MKK','Station'),
    ('MKLA','Jackson','United States','MKL','Jackson',68140,'MKL','Station'),
    ('MLBA','Melbourne','United States','MLB','Melbourne',68178,'MLB','Station'),
    ('MLIA','Moline','United States','MLI','Moline',68185,'MLI','Station'),
    ('MLUA','Monroe','United States','MLU','Monroe',68197,'MLU','Station'),
    ('MMHA','Mammoth Lakes','United States','MMH','Mammoth Lakes',68232,'MMH','Station'),
    ('MOBA','Mobile','United States','MOB','Mobile Municipal Arpt',68322,'MOB','Station'),
    ('MOTA','Minot','United States','MOT','Minot International',68340,'MOT','Station'),
    ('MQTA','Marquette','United States','MQT','Marquette',68436,'MQT','Station'),
    ('MRYA','Carmel','United States','MRY','Carmel Monterey Peninsula',68489,'MRY','Station'),
    ('MSNA','Madison','United States','MSN','Madison',68526,'MSN','Station'),
    ('MSOA','Missoula','United States','MSO','Missoula',68527,'MSO','Station'),
    ('MSPA','Minneapolis','United States','MSP','Minneapolis St Paul',68528,'MSP','Station'),
    ('MSSA','Massena','United States','MSS','Massena',68531,'MSS','Station'),
    ('MSYA','New Orleans','United States','MSY','New Orleans Louis Armstrong',68537,'MSY','Station');
INSERT INTO places (CityId, CityName, CountryName, IataCode, Name, PlaceId, SkyscannerCode, Type) values
    ('MTJA','Montrose','United States','MTJ','Montrose',68570,'MTJ','Station'),
    ('MUEA','Kamuela','United States','MUE','Kamuela',68613,'MUE','Station'),
    ('MVYA','Martha''s Vineyard','United States','MVY','Martha''s Vineyard',68681,'MVY','Station'),
    ('MYRA','Myrtle Beach','United States','MYR','Myrtle Beach AFB',68818,'MYR','Station'),
    ('OAJA','Jacksonville','United States','OAJ','Jacksonville',72266,'OAJ','Station'),
    ('OAKA','Oakland','United States','OAK','Oakland Metropolitan Oak',72267,'OAK','Station'),
    ('OGGA','Kahului','United States','OGG','Maui Kahului',72551,'OGG','Station'),
    ('OGSA','Ogdensburg','United States','OGS','Ogdensburg',72563,'OGS','Station'),
    ('OKCA','Oklahoma City','United States','OKC','Oklahoma City Will Rogers World',72739,'OKC','Station'),
    ('OMAA','Omaha','United States','OMA','Omaha Eppley Airfield',72833,'OMA','Station'),
    ('OMEA','Nome','United States','OME','Nome',72837,'OME','Station'),
    ('ONTA','Ontario','United States','ONT','Ontario International',72900,'ONT','Station'),
    ('CHIA','Chicago','United States','ORD','Chicago O''Hare International',73076,'ORD','Station'),
    ('ORFA','Norfolk','United States','ORF','Norfolk International',73078,'ORF','Station'),
    ('ORHA','Worcester','United States','ORH','Worcester',73080,'ORH','Station'),
    ('OTHA','North Bend','United States','OTH','North Bend',73176,'OTH','Station'),
    ('PAEA','Everett','United States','PAE','Everett',74565,'PAE','Station'),
    ('PAHA','Paducah','United States','PAH','Paducah',74568,'PAH','Station'),
    ('PLBA','Plattsburgh','United States','PBG','Plattsburgh AFB',74615,'PBG','Station'),
    ('PBIA','West Palm Beach','United States','PBI','West Palm Beach International',74617,'PBI','Station'),
    ('PDXA','Portland','United States','PDX','Portland',74728,'PDX','Station'),
    ('PGDA','Punta Gorda','United States','PGD','Punta Gorda',74852,'PGD','Station'),
    ('PGVA','Greenville','United States','PGV','Pitt-Greenville',74870,'PGV','Station'),
    ('PHFA','Newport News','United States','PHF','Newport News / Williamsb',74902,'PHF','Station'),
    ('PHLA','Philadelphia','United States','PHL','Philadelphia International',74908,'PHL','Station'),
    ('PHXA','Phoenix','United States','PHX','Phoenix Sky Harbor',74920,'PHX','Station'),
    ('PIAA','Peoria','United States','PIA','Greater Peoria',74945,'PIA','Station'),
    ('LULA','Laurel','United States','PIB','Hattiesburg-Laurel',74946,'PIB','Station'),
    ('PIHA','Pocatello','United States','PIH','Pocatello',74952,'PIH','Station'),
    ('PIRA','Pierre','United States','PIR','Pierre',74962,'PIR','Station'),
    ('PITA','Pittsburgh','United States','PIT','Pittsburgh International',74964,'PIT','Station'),
    ('PLNA','Pellston','United States','PLN','Pellston',75102,'PLN','Station'),
    ('PNSA','Pensacola','United States','PNS','Pensacola',75203,'PNS','Station'),
    ('PQIA','Presque Isle','United States','PQI','Presque Isle',75337,'PQI','Station'),
    ('PRCA','Prescott','United States','PRC','Prescott',75379,'PRC','Station'),
    ('PSCA','Pasco','United States','PSC','Pasco',75427,'PSC','Station'),
    ('PSGA','Petersburg','United States','PSG','Petersburg',75431,'PSG','Station'),
    ('PSPA','Palm Springs','United States','PSP','Palm Springs International',75440,'PSP','Station'),
    ('PUBA','Pueblo','United States','PUB','Pueblo',75522,'PUB','Station'),
    ('PUWA','Pullman','United States','PUW','Pullman',75543,'PUW','Station'),
    ('PVCA','Provincetown','United States','PVC','Provincetown',75571,'PVC','Station'),
    ('PVDA','Providence','United States','PVD','Providence',75572,'PVD','Station'),
    ('PVUA','Provo','United States','PVU','Provo',75589,'PVU','Station'),
    ('PWMA','Portland','United States','PWM','Portland',75629,'PWM','Station'),
    ('RAPA','Rapid City','United States','RAP','Rapid City Regional',79184,'RAP','Station'),
    ('RDDA','Redding','United States','RDD','Redding',79316,'RDD','Station'),
    ('RDMA','Redmond','United States','RDM','Redmond',79325,'RDM','Station'),
    ('RDUA','Durham','United States','RDU','Raleigh / Durham',79333,'RDU','Station'),
    ('RHIA','Rhinelander','United States','RHI','Rhinelander',79513,'RHI','Station'),
    ('RICA','Richmond','United States','RIC','Richmond',79555,'RIC','Station'),
    ('RKDA','Rockland','United States','RKD','Rockland',79652,'RKD','Station'),
    ('RKSA','Rock Springs','United States','RKS','Rock Springs',79667,'RKS','Station'),
    ('RNOA','Reno','United States','RNO','Reno / Tahoe',79807,'RNO','Station'),
    ('ROAA','Roanoke','United States','ROA','Roanoke',79841,'ROA','Station'),
    ('ROCA','Rochester','United States','ROC','Rochester',79843,'ROC','Station'),
    ('ROWA','Roswell','United States','ROW','Roswell',79863,'ROW','Station'),
    ('RSTA','Rochester','United States','RST','Rochester Municipal',80052,'RST','Station'),
    ('FMYA','Fort Myers','United States','RSW','Fort Myers Southwest Florida Reg',80055,'RSW','Station'),
    ('RUTA','Rutland','United States','RUT','Rutland',80148,'RUT','Station'),
    ('ZSHA','Santa Fe','United States','SAF','Santa Fe',81478,'SAF','Station'),
    ('SANA','San Diego','United States','SAN','San Diego International',81486,'SAN','Station'),
    ('SATA','San Antonio','United States','SAT','San Antonio International',81492,'SAT','Station'),
    ('SAVA','Savannah','United States','SAV','Savannah / Hilton Head',81494,'SAV','Station'),
    ('SBAA','Santa Barbara','United States','SBA','Santa Barbara Municipal',81521,'SBA','Station'),
    ('SBNA','South Bend','United States','SBN','South Bend',81534,'SBN','Station'),
    ('CSLA','San Luis Obispo','United States','SBP','San Luis Obispo County',81536,'SBP','Station'),
    ('SBYA','Salisbury-Ocean City','United States','SBY','Salisbury-Ocean City',81545,'SBY','Station'),
    ('SCEA','State College','United States','SCE','State College',81573,'SCE','Station'),
    ('SDFA','Louisville','United States','SDF','Louisville Standiford Field',81622,'SDF','Station'),
    ('SEAA','Seattle','United States','SEA','Seattle / Tacoma International',81665,'SEA','Station'),
    ('SFOA','San Francisco','United States','SFO','San Francisco International',81727,'SFO','Station'),
    ('SGFA','Springfield','United States','SGF','Springfield-Branson Rg',81766,'SGF','Station'),
    ('SGUA','Saint George','United States','SGU','Saint George',81781,'SGU','Station'),
    ('SHDA','Staunton','United States','SHD','Staunton',81812,'SHD','Station'),
    ('SHVA','Shreveport','United States','SHV','Shreveport Regional',81830,'SHV','Station'),
    ('SITA','Sitka','United States','SIT','Sitka',81876,'SIT','Station'),
    ('SJCA','San Jose','United States','SJC','San Jose International',81907,'SJC','Station'),
    ('SJTA','San Angelo','United States','SJT','San Angelo Mathis Fld',81924,'SJT','Station'),
    ('SLCA','Salt Lake City','United States','SLC','Salt Lake City',82003,'SLC','Station'),
    ('SLKA','Saranac Lake','United States','SLK','Saranac Lake',82011,'SLK','Station'),
    ('SLNA','Salina','United States','SLN','Salina',82014,'SLN','Station'),
    ('SACA','Sacramento','United States','SMF','Sacramento International',82054,'SMF','Station'),
    ('SMXA','Santa Maria','United States','SMX','Santa Maria',82072,'SMX','Station'),
    ('SNAA','Santa Ana','United States','SNA','Santa Ana John Wayne',82097,'SNA','Station'),
    ('SPIA','Springfield','United States','SPI','Springfield',82201,'SPI','Station'),
    ('SPSA','Wichita Falls','United States','SPS','Wichita Falls Sheppard AFB',82211,'SPS','Station'),
    ('SRQA','Sarasota','United States','SRQ','Sarasota',82305,'SRQ','Station'),
    ('STLA','St Louis','United States','STL','St Louis',82396,'STL','Station'),
    ('STSA','Santa Rosa','United States','STS','Santa Rosa',82403,'STS','Station'),
    ('SUNA','Hailey','United States','SUN','Hailey',82446,'SUN','Station'),
    ('SUXA','Sioux City','United States','SUX','Sioux City',82456,'SUX','Station'),
    ('NYCA','New York','United States','SWF','Stewart International',82534,'SWF','Station'),
    ('SWOA','Stillwater','United States','SWO','Stillwater',82543,'SWO','Station'),
    ('SYRA','Syracuse','United States','SYR','Syracuse',82642,'SYR','Station'),
    ('TEXA','Telluride','United States','TEX','Telluride',83992,'TEX','Station'),
    ('TLHA','Tallahassee','United States','TLH','Tallahassee',84312,'TLH','Station'),
    ('TOLA','Toledo','United States','TOL','Toledo Express',84460,'TOL','Station'),
    ('TPAA','Tampa','United States','TPA','Tampa International',84497,'TPA','Station'),
    ('TRIA','Kingsport','United States','TRI','Tri-Cities',84601,'TRI','Station'),
    ('PHLA','Philadelphia','United States','TTN','Philadelphia Trenton-Mercer',84702,'TTN','Station'),
    ('TULB','Tulsa','United States','TUL','Tulsa International',84748,'TUL','Station'),
    ('TUSA','Tucson','United States','TUS','Tucson International',84755,'TUS','Station'),
    ('TVCA','Traverse City','United States','TVC','Traverse City',84787,'TVC','Station'),
    ('TVFA','Thief River Falls','United States','TVF','Thief River Falls',84790,'TVF','Station'),
    ('TWFA','Twin Falls','United States','TWF','Twin Falls',84838,'TWF','Station'),
    ('TXKA','Texarkana','United States','TXK','Texarkana',84891,'TXK','Station'),
    ('TYRA','Tyler','United States','TYR','Tyler',84946,'TYR','Station'),
    ('TYSA','Knoxville','United States','TYS','Knoxville',84947,'TYS','Station'),
    ('UINA','Quincy','United States','UIN','Quincy',86478,'UIN','Station'),
    ('USAA','Concord','United States','USA','Concord Regional',86945,'USA','Station'),
    ('VCTA','Victoria','United States','VCT','Victoria',88500,'VCT','Station'),
    ('VELA','Vernal','United States','VEL','Vernal',88588,'VEL','Station'),
    ('VLDA','Valdosta','United States','VLD','Valdosta Regional',88916,'VLD','Station'),
    ('VPSA','Valparaiso','United States','VPS','Valparaiso Ft. Walton Beach',89123,'VPS','Station'),
    ('WYSA','West Yellowstone','United States','WYS','West Yellowstone',91859,'WYS','Station'),
    ('FYVA','Fayetteville','United States','XNA','Fayetteville Northwest Arkansas Rgn',93617,'XNA','Station'),
    ('YAKA','Yakutat','United States','YAK','Yakutat',95307,'YAK','Station'),
    ('YKMA','Yakima','United States','YKM','Yakima Air Terminal',95789,'YKM','Station'),
    ('YUMA','Yuma','United States','YUM','Yuma International',96269,'YUM','Station');

unlock tables;
